import type { Mesh, Vec3 } from "../geometry/types.js";
import { colorKey, resolveColor, type Rgb, type Palette } from "../palette.js";

const f = (n: number): string => n.toFixed(4);

/**
 * Name a material after the group of faces sharing it: the direction for a
 * direction palette, or slot and kind for a slot one.
 */
const materialName = (key: string, palette: Palette): string =>
  palette.mode === "direction" ? `dir_${key}` : `slot${key}`;

export interface ObjExport {
  obj: string;
  mtl: string;
}

export function toObj(
  mesh: Mesh,
  palette: Palette,
  mtlFileName: string,
): ObjExport {
  const vertexLines: string[] = [];
  const normalLines: string[] = [];
  const index = new Map<string, number>();
  const normalIndex = new Map<string, number>();

  const vertexId = (v: Vec3): number => {
    const key = `${f(v.x)}/${f(v.y)}/${f(v.z)}`;
    const existing = index.get(key);
    if (existing !== undefined) return existing;
    vertexLines.push(`v ${f(v.x)} ${f(v.y)} ${f(v.z)}`);
    const id = vertexLines.length;
    index.set(key, id);
    return id;
  };

  const normalId = (v: Vec3): number => {
    const key = `${f(v.x)}/${f(v.y)}/${f(v.z)}`;
    const existing = normalIndex.get(key);
    if (existing !== undefined) return existing;
    normalLines.push(`vn ${f(v.x)} ${f(v.y)} ${f(v.z)}`);
    const id = normalLines.length;
    normalIndex.set(key, id);
    return id;
  };

  // Group faces by material so the OBJ carries one usemtl run per colour. The
  // colour is captured here, where the triangle is in hand, rather than parsed
  // back out of the material name later.
  const groups = new Map<string, { color: Rgb; faces: string[] }>();
  for (const tri of mesh.triangles) {
    const name = materialName(colorKey(palette, tri), palette);
    const vs = [vertexId(tri.a), vertexId(tri.b), vertexId(tri.c)];
    const n = normalId(tri.normal);
    const face = `f ${vs.map((v) => `${v}//${n}`).join(" ")}`;
    const bucket = groups.get(name);
    if (bucket) bucket.faces.push(face);
    else groups.set(name, { color: resolveColor(palette, tri), faces: [face] });
  }

  const objLines: string[] = [
    "# Generated by logo-generator",
    `# palette: ${palette.name}`,
    `mtllib ${mtlFileName}`,
    "",
    "o Logo",
    ...vertexLines,
    ...normalLines,
    "",
  ];
  for (const [name, group] of groups) {
    objLines.push(`usemtl ${name}`, ...group.faces, "");
  }

  const mtlLines: string[] = [
    "# Generated by logo-generator",
    `# palette: ${palette.name}`,
    "",
  ];
  for (const [name, group] of groups) {
    const c = group.color;
    const kd = [c.r / 255, c.g / 255, c.b / 255].map((n) => n.toFixed(4));
    mtlLines.push(
      `newmtl ${name}`,
      "\tNs 10.0000",
      "\td 1.0000",
      "\tillum 2",
      "\tKa 0.0000 0.0000 0.0000",
      `\tKd ${kd.join(" ")}`,
      "\tKs 0.0000 0.0000 0.0000",
      // The original is self-illuminated; emissive matches that flat look.
      `\tKe ${kd.join(" ")}`,
      "",
    );
  }

  return { obj: objLines.join("\n"), mtl: mtlLines.join("\n") };
}
